### PR TITLE
Allows auto-mapping of System Environment Variables

### PR DESCRIPTION
**Pull request by The-Funk**
Replaces System.getProperty() with System.getenv() in order to allow for pulling environment variables from the system environment instead of the Java environment.

Replaces a few if statements with guard clauses for readability. (housekeeping while I'm here)

KubernetesWithTemplatesIT shouldHelmManifestsBeGenerated test fails.
templates/configmap.yaml contains exactly one copy of duplicate data.

Looking into that after lunch to make sure I didn't inadvertently cause that test to fail.

### CODE REVIEW

**Review by Sgitario — CHANGES_REQUESTED** [review]
There are much more changes than required and also formatting issues.
Please, keep your changes minimal as it might have side effects for other users.

**Comment by The-Funk** [comment]
Hi @Sgitario 

I fixed the opening bracket issue. Sorry, I frequently break style guidelines like that.

It looks like a lot of changes from the diff but in reality I just unwrapped one or two if statements and replaced them with guard clauses.

**Review by Sgitario — CHANGES_REQUESTED** [review]
Doing biased formatting changes in unrelated changes (support environment props) makes the GIT history hell, please revert these changes and do only the minimum that is required to support env props. 

Also, we should keep supporting system properties as using `System.getenv` will not work for system properties as it was before. 

Some tests should be added as well.

**Comment by The-Funk** [comment]
@Sgitario That's fair. I'll revert formatting changes and then implement.

I need to check the expected behavior of getenv and getProperty to make sure they return null and not empty string in the event that a key doesn't exist. 

If so then we could favor getProperty since the Java Environment is closer to the workspace and then if null there, fallback to using getenv to consult the System variables. If null there, then fallback to a default provided value if there is one, else empty.

If empty string is the default then we could still follow the same formula above but would have to check all system properties to find if there is a matching key or not. That would be slightly slower but I don't think that's a problem.

Does this sound good?

1. Consult Java Environment (and if no key...)
2. Consult System (and if no key...)
3. Consult fallback value (and if no value...)
4. Apply empty

**Comment by Sgitario** [comment]
This is what I had in mind, but avoiding reading the property twice, plus adding some test coverage. 
https://github.com/quarkiverse/quarkus-helm/pull/194 should address this issue, anyway thanks for looking into this!
Superseded by https://github.com/quarkiverse/quarkus-helm/pull/194.

**Pull request closed without merging**
