### PR TITLE
Additional resources to include Rancher Charts files and requirements

### PR DESCRIPTION
**Pull request by Sgitario**
Fix https://github.com/quarkiverse/quarkus-helm/issues/116

Note that perhaps we should include all the files in the input folder, but for now, I don't want to open this door as it might open a can of worms.

### CODE REVIEW

**Comment by Sgitario** [comment]
cc @ThoSap

**Comment by ThoSap** [comment]
Would it make sense to specify the supported files here?
https://quarkiverse.github.io/quarkiverse-docs/quarkus-helm/dev/index.html#quarkus-helm_quarkus.helm.input-directory

**Comment by Sgitario** [comment]
> Would it make sense to specify the supported files here? https://quarkiverse.github.io/quarkiverse-docs/quarkus-helm/dev/index.html#quarkus-helm_quarkus.helm.input-directory

Right! PR updated.

**Comment by ThoSap** [comment]
Thanks!

**Pull request merged**
