### PR TITLE
feat: Add option to make clearing output directory optional

### PR DESCRIPTION
**Pull request by antssilva96**

### CODE REVIEW

**Comment by antssilva96** [comment]
In our use case is important because we want to keep the downloaded .tgz of the dependencies in the charts file without it being deleted every time we compile the project.

**Comment by antssilva96** [comment]
I think this still makes sense with #63.

Another approach would be to never clear the output repository because if the default is not in target users can always use `mvn clean package` instead of  `mvn package` if they want it cleared.

**Comment by Sgitario** [comment]
If users do not want to clear the output directory, they do not use the `mvn clean package`, but `mvn package`. Still don't think why we should overcomplicate the logic here.

**Comment by antssilva96** [comment]
Exactly! But the current code is always clearing the output folder.

My issue is the following: if in #63 I pass an absolute path for my documents for some reason, will it delete my entire folder ?

**Comment by Sgitario** [comment]
> Exactly! But the current code is always clearing the output folder.
> 
> My issue is the following: if in #63 I pass an absolute path for my documents for some reason, will it delete my entire folder ?

Yes, it will delete the entire folder. The problem without not deleting the folder is that it duplicates the resources among other side effects. That's why we decided to always delete the folder. 
I'm thinking that when using an absolute folder, we should check that it's empty and fail if it's not. wdyt?

**Comment by antssilva96** [comment]
> I'm thinking that when using an absolute folder, we should check that it's empty and fail if it's not. wdyt?

Yeah that sounds good!

**Pull request closed without merging**
